export type DashboardLocale = "zh-CN" | "zh-TW" | "en" | "ja";

export function normalizeDashboardLocale(lang?: string): DashboardLocale {
  if (lang === "zh-CN" || lang === "zh-cn") return "zh-CN";
  if (lang === "zh-TW" || lang === "zh-tw") return "zh-TW";
  if (lang === "en") return "en";
  return "ja";
}

const copy = {
  "zh-CN": {
    shellBadge: "Dashboard Shell / Business View Layer",
    shellWorkspaceTitle: "Dashboard V3 是当前主工作区。",
    shellFallbackText: "Legacy DashboardHomeV2 仍作为下方回退保留。",
    contractSummaryTitle: "Dashboard V3 合同摘要",
    contractSourceRange: (source: string, range: string) => `source: ${source} · range: ${range}`,
    contractKpi: (n: number) => `KPI ${n}`,
    contractTrends: (n: number) => `Trends ${n}`,
    contractDistributions: (n: number) => `Distributions ${n}`,
    contractAlerts: (n: number) => `Alerts ${n}`,
    contractExplain: (n: number) => `Explain ${n}`,
    quickBusinessType: "业务类型",
    quickChangeType: "更改业务类型",
    cockpitEyebrow: "Amazon 经营驾驶舱",
    cockpitOperatingOverview: "经营总览",
    cockpitSummary: "在一个页面里查看销售、入金、利润参考、对账准备度与税理士交付状态。",
    statusSource: "数据来源",
    statusRange: "范围",
    statusPlan: "套餐",
    statusAccess: "访问状态",
    statusAlerts: "告警数",
    planCurrent: "当前套餐",
    planAccessMode: "访问状态",
    planTrialRemaining: "试用剩余",
    planStatusTitle: "订阅状态",
    accessModeCopy: {
      active: "当前为正常付费访问。",
      trial: "当前为试用期，已临时解锁完整体验。",
      readonly: "当前为只读模式，仅可查看历史数据。",
    },
    accessModeLabel: {
      active: "有效",
      trial: "试用中",
      readonly: "只读",
    },
    planLabel: {
      starter: "Starter",
      standard: "Standard",
      premium: "Premium",
    },
    trendReportChart: "报表图",
    trendSimpleChart: "趋势",
    trendLatest: "最新",
    trendMax: "最大",
    trendMin: "最小",
    trendDelta: "变化",
    trendAmazonPrimary: "销售 / 入金趋势",
    trendAmazonSecondary: "订单 / 差额趋势",
    trendEcPrimary: "销售 / 回收趋势",
    trendEcSecondary: "未回收 / 费用趋势",
    trendAmazonPrimaryHint: "查看销售与入金之间的距离",
    trendAmazonSecondaryHint: "查看订单趋势与差额变化",
    trendEcPrimaryHint: "查看销售与回收之间的距离",
    trendEcSecondaryHint: "查看未回收与费用变化",
    distributionEnhanced: "分布 + 构成",
    distributionBasic: "分布视图",
    distributionAmazonPrimary: "差额构成",
    distributionAmazonSecondary: "渠道构成",
    distributionEcPrimary: "费用构成",
    distributionEcSecondary: "渠道构成",
    anomalyHigh: "高优先级",
    anomalyMedium: "中优先级",
    anomalyLow: "低优先级",
    anomalyPriority: "优先级",
    anomalyHintAmazonHigh: "优先查看差额构成与 explain 预览",
    anomalyHintAmazonMedium: "查看广告费与退款项目",
    anomalyHintAmazonLow: "持续监控趋势",
    anomalyHintEcHigh: "优先查看费用构成与警示",
    anomalyHintEcMedium: "查看回收差额",
    anomalyHintEcLow: "持续监控趋势",
    reconciliationTitle: "对账健康度",
    reconciliationSummary: "让缺失附件、未匹配记录和审核队列在 Dashboard 上可见。",
    reconciliationBadge: "Dashboard 行动中心",
    reconciliationInvoice: "缺少发票",
    reconciliationBank: "缺少银行凭证",
    reconciliationReview: "待审核",
    reconciliationPayout: "未匹配入金项",
    reconciliationPlaceholder: "可下钻占位",
    accountantTitle: "税理士交付准备度",
    accountantSummary: "在月末交付前明确显示缺票和导出准备状态。",
    accountantInvoiceReadiness: "发票准备度",
    accountantExplainCoverage: "解释覆盖度",
    accountantReviewBlockers: "审核阻塞项",
    accountantChecklistTitle: "月末交付清单",
    accountantChecklistSummary: "为税理士导出准备提供轻量协作面板。",
    accountantChecklist: [
      "销售汇总已准备",
      "费用附件已检查",
      "缺票队列已检查",
      "入金不匹配队列已检查",
      "库存参考已导出",
      "利润参考已复核",
    ],
    businessLabels: {
      amazon: "Amazon 视图",
      ec: "EC 视图",
      restaurant: "餐饮视图",
      generic: "通用中小企业视图",
    },
    businessDescriptions: {
      amazon: "以 Amazon 销售、入金、差额理解为核心的经营视图",
      ec: "面向电商销售的收入、费用与收益管理视图",
      restaurant: "面向餐饮业务的销售、成本与利润确认视图",
      generic: "面向通用中小企业的经营管理视图",
    },
  },
  "zh-TW": {
    shellBadge: "Dashboard Shell / Business View Layer",
    shellWorkspaceTitle: "Dashboard V3 是目前的主要工作區。",
    shellFallbackText: "Legacy DashboardHomeV2 仍保留作為下方回退。",
    contractSummaryTitle: "Dashboard V3 合約摘要",
    contractSourceRange: (source: string, range: string) => `source: ${source} · range: ${range}`,
    contractKpi: (n: number) => `KPI ${n}`,
    contractTrends: (n: number) => `Trends ${n}`,
    contractDistributions: (n: number) => `Distributions ${n}`,
    contractAlerts: (n: number) => `Alerts ${n}`,
    contractExplain: (n: number) => `Explain ${n}`,
    quickBusinessType: "業務類型",
    quickChangeType: "變更業務類型",
    cockpitEyebrow: "Amazon 經營駕駛艙",
    cockpitOperatingOverview: "經營總覽",
    cockpitSummary: "在同一頁面查看銷售、入金、利潤參考、對帳準備度與稅理士交付狀態。",
    statusSource: "資料來源",
    statusRange: "範圍",
    statusPlan: "方案",
    statusAccess: "存取狀態",
    statusAlerts: "警示數",
    planCurrent: "目前方案",
    planAccessMode: "存取狀態",
    planTrialRemaining: "試用剩餘",
    planStatusTitle: "訂閱狀態",
    accessModeCopy: {
      active: "目前為正常付費存取。",
      trial: "目前為試用期，已暫時解鎖完整體驗。",
      readonly: "目前為唯讀模式，只能查看歷史資料。",
    },
    accessModeLabel: {
      active: "有效",
      trial: "試用中",
      readonly: "唯讀",
    },
    planLabel: {
      starter: "Starter",
      standard: "Standard",
      premium: "Premium",
    },
    trendReportChart: "報表圖",
    trendSimpleChart: "趨勢",
    trendLatest: "最新",
    trendMax: "最大",
    trendMin: "最小",
    trendDelta: "變化",
    trendAmazonPrimary: "銷售 / 入金趨勢",
    trendAmazonSecondary: "訂單 / 差額趨勢",
    trendEcPrimary: "銷售 / 回收趨勢",
    trendEcSecondary: "未回收 / 費用趨勢",
    trendAmazonPrimaryHint: "查看銷售與入金之間的距離",
    trendAmazonSecondaryHint: "查看訂單趨勢與差額變化",
    trendEcPrimaryHint: "查看銷售與回收之間的距離",
    trendEcSecondaryHint: "查看未回收與費用變化",
    distributionEnhanced: "分布 + 構成",
    distributionBasic: "分布視圖",
    distributionAmazonPrimary: "差額構成",
    distributionAmazonSecondary: "渠道構成",
    distributionEcPrimary: "費用構成",
    distributionEcSecondary: "渠道構成",
    anomalyHigh: "高優先級",
    anomalyMedium: "中優先級",
    anomalyLow: "低優先級",
    anomalyPriority: "優先級",
    anomalyHintAmazonHigh: "優先查看差額構成與 explain 預覽",
    anomalyHintAmazonMedium: "查看廣告費與退款項目",
    anomalyHintAmazonLow: "持續監控趨勢",
    anomalyHintEcHigh: "優先查看費用構成與警示",
    anomalyHintEcMedium: "查看回收差額",
    anomalyHintEcLow: "持續監控趨勢",
    reconciliationTitle: "對帳健康度",
    reconciliationSummary: "讓缺失附件、未匹配記錄與審核佇列在 Dashboard 上可見。",
    reconciliationBadge: "Dashboard 行動中心",
    reconciliationInvoice: "缺少發票",
    reconciliationBank: "缺少銀行憑證",
    reconciliationReview: "待審核",
    reconciliationPayout: "未匹配入金項",
    reconciliationPlaceholder: "可下鑽占位",
    accountantTitle: "稅理士交付準備度",
    accountantSummary: "在月末交付前明確顯示缺票與匯出準備狀態。",
    accountantInvoiceReadiness: "發票準備度",
    accountantExplainCoverage: "解釋覆蓋度",
    accountantReviewBlockers: "審核阻塞項",
    accountantChecklistTitle: "月末交付清單",
    accountantChecklistSummary: "為稅理士匯出準備提供輕量協作面板。",
    accountantChecklist: [
      "銷售彙總已準備",
      "費用附件已檢查",
      "缺票佇列已檢查",
      "入金不匹配佇列已檢查",
      "庫存參考已匯出",
      "利潤參考已複核",
    ],
    businessLabels: {
      amazon: "Amazon 視圖",
      ec: "EC 視圖",
      restaurant: "餐飲視圖",
      generic: "通用中小企業視圖",
    },
    businessDescriptions: {
      amazon: "以 Amazon 銷售、入金、差額理解為核心的經營視圖",
      ec: "面向電商銷售的收入、費用與收益管理視圖",
      restaurant: "面向餐飲業務的銷售、成本與利潤確認視圖",
      generic: "面向通用中小企業的經營管理視圖",
    },
  },
  en: {
    shellBadge: "Dashboard Shell / Business View Layer",
    shellWorkspaceTitle: "Dashboard V3 is the primary workspace.",
    shellFallbackText: "Legacy DashboardHomeV2 remains as fallback below.",
    contractSummaryTitle: "Dashboard V3 contract summary",
    contractSourceRange: (source: string, range: string) => `source: ${source} · range: ${range}`,
    contractKpi: (n: number) => `KPI ${n}`,
    contractTrends: (n: number) => `Trends ${n}`,
    contractDistributions: (n: number) => `Distributions ${n}`,
    contractAlerts: (n: number) => `Alerts ${n}`,
    contractExplain: (n: number) => `Explain ${n}`,
    quickBusinessType: "Business Type",
    quickChangeType: "Change business type",
    cockpitEyebrow: "Amazon dashboard cockpit",
    cockpitOperatingOverview: "Operating overview",
    cockpitSummary: "Review sales, payout, profit reference, reconciliation readiness, and accountant handoff in one place.",
    statusSource: "source",
    statusRange: "range",
    statusPlan: "plan",
    statusAccess: "access",
    statusAlerts: "alerts",
    planCurrent: "current plan",
    planAccessMode: "access mode",
    planTrialRemaining: "trial remaining",
    planStatusTitle: "subscription status",
    accessModeCopy: {
      active: "Paid access is active.",
      trial: "Premium trial is active. Full experience is temporarily unlocked.",
      readonly: "Readonly mode is active. History is visible, but action pages are locked.",
    },
    accessModeLabel: {
      active: "active",
      trial: "trial",
      readonly: "readonly",
    },
    planLabel: {
      starter: "Starter",
      standard: "Standard",
      premium: "Premium",
    },
    trendReportChart: "report chart",
    trendSimpleChart: "trend",
    trendLatest: "latest",
    trendMax: "max",
    trendMin: "min",
    trendDelta: "delta",
    trendAmazonPrimary: "Sales / Payout trend",
    trendAmazonSecondary: "Orders / Gap trend",
    trendEcPrimary: "Sales / Recovery trend",
    trendEcSecondary: "Unrecovered / Expense trend",
    trendAmazonPrimaryHint: "Check the distance between sales and payout",
    trendAmazonSecondaryHint: "Check order trend and gap movement",
    trendEcPrimaryHint: "Check the distance between sales and recovery",
    trendEcSecondaryHint: "Check unrecovered balance and expense movement",
    distributionEnhanced: "distribution + composition",
    distributionBasic: "distribution view",
    distributionAmazonPrimary: "Gap breakdown",
    distributionAmazonSecondary: "Channel mix",
    distributionEcPrimary: "Expense breakdown",
    distributionEcSecondary: "Channel mix",
    anomalyHigh: "High priority",
    anomalyMedium: "Medium priority",
    anomalyLow: "Low priority",
    anomalyPriority: "priority",
    anomalyHintAmazonHigh: "Check gap breakdown and explain preview first",
    anomalyHintAmazonMedium: "Check ads and refund items",
    anomalyHintAmazonLow: "Continue monitoring the trend",
    anomalyHintEcHigh: "Check expense breakdown and alerts first",
    anomalyHintEcMedium: "Check recovery gap",
    anomalyHintEcLow: "Continue monitoring the trend",
    reconciliationTitle: "Reconciliation health",
    reconciliationSummary: "Make missing attachments, unmatched records, and review queue visible from the dashboard.",
    reconciliationBadge: "dashboard action center",
    reconciliationInvoice: "missing invoices",
    reconciliationBank: "missing bank proofs",
    reconciliationReview: "pending review",
    reconciliationPayout: "unmatched payout items",
    reconciliationPlaceholder: "drilldown-ready placeholder",
    accountantTitle: "Accountant handoff readiness",
    accountantSummary: "Make missing invoice and export readiness visible before month-end handoff.",
    accountantInvoiceReadiness: "invoice readiness",
    accountantExplainCoverage: "explain coverage",
    accountantReviewBlockers: "review blockers",
    accountantChecklistTitle: "Month-end handoff checklist",
    accountantChecklistSummary: "A lightweight collaboration surface for accountant export readiness.",
    accountantChecklist: [
      "Sales summary prepared",
      "Expense attachments reviewed",
      "Missing invoice queue checked",
      "Payout mismatch queue checked",
      "Inventory reference exported",
      "Profit reference reviewed",
    ],
    businessLabels: {
      amazon: "Amazon View",
      ec: "EC View",
      restaurant: "Restaurant View",
      generic: "Generic SMB View",
    },
    businessDescriptions: {
      amazon: "An operating view centered on understanding Amazon sales, payout, and gap.",
      ec: "A revenue, expense, and profit management view for ecommerce operations.",
      restaurant: "A sales, cost, and profit confirmation view for restaurant operations.",
      generic: "A business management view for general SMB operations.",
    },
  },
  ja: {
    shellBadge: "Dashboard Shell / Business View Layer",
    shellWorkspaceTitle: "Dashboard V3 が現在のメインワークスペースです。",
    shellFallbackText: "旧 DashboardHomeV2 は下部のフォールバックとして残しています。",
    contractSummaryTitle: "Dashboard V3 契約サマリー",
    contractSourceRange: (source: string, range: string) => `source: ${source} · range: ${range}`,
    contractKpi: (n: number) => `KPI ${n}`,
    contractTrends: (n: number) => `Trends ${n}`,
    contractDistributions: (n: number) => `Distributions ${n}`,
    contractAlerts: (n: number) => `Alerts ${n}`,
    contractExplain: (n: number) => `Explain ${n}`,
    quickBusinessType: "事業タイプ",
    quickChangeType: "事業タイプを変更",
    cockpitEyebrow: "Amazon ダッシュボードコックピット",
    cockpitOperatingOverview: "運営概要",
    cockpitSummary: "売上、入金、利益参考、照合準備度、税理士受け渡し状況を一つの画面で確認します。",
    statusSource: "データソース",
    statusRange: "期間",
    statusPlan: "プラン",
    statusAccess: "アクセス状態",
    statusAlerts: "アラート数",
    planCurrent: "現在のプラン",
    planAccessMode: "アクセス状態",
    planTrialRemaining: "試用残日数",
    planStatusTitle: "契約ステータス",
    accessModeCopy: {
      active: "現在は通常の有料アクセスです。",
      trial: "現在は試用期間中で、フル体験が一時的に開放されています。",
      readonly: "現在は readonly mode で、履歴閲覧のみ可能です。",
    },
    accessModeLabel: {
      active: "有効",
      trial: "試用中",
      readonly: "閲覧のみ",
    },
    planLabel: {
      starter: "Starter",
      standard: "Standard",
      premium: "Premium",
    },
    trendReportChart: "レポート図",
    trendSimpleChart: "推移",
    trendLatest: "最新",
    trendMax: "最大",
    trendMin: "最小",
    trendDelta: "変化",
    trendAmazonPrimary: "売上 / 入金トレンド",
    trendAmazonSecondary: "注文 / 差額トレンド",
    trendEcPrimary: "売上 / 回収トレンド",
    trendEcSecondary: "未回収 / 費用トレンド",
    trendAmazonPrimaryHint: "売上と入金の距離感を確認",
    trendAmazonSecondaryHint: "注文推移と差額変化を確認",
    trendEcPrimaryHint: "売上と回収の距離感を確認",
    trendEcSecondaryHint: "未回収と費用変化を確認",
    distributionEnhanced: "分布 + 構成",
    distributionBasic: "分布ビュー",
    distributionAmazonPrimary: "差額構成",
    distributionAmazonSecondary: "チャネル構成",
    distributionEcPrimary: "費用構成",
    distributionEcSecondary: "チャネル構成",
    anomalyHigh: "高優先度",
    anomalyMedium: "中優先度",
    anomalyLow: "低優先度",
    anomalyPriority: "優先度",
    anomalyHintAmazonHigh: "差額構成と explain preview を先に確認",
    anomalyHintAmazonMedium: "広告費・返金項目を確認",
    anomalyHintAmazonLow: "推移を継続監視",
    anomalyHintEcHigh: "費用構成と alerts を先に確認",
    anomalyHintEcMedium: "回収との差を確認",
    anomalyHintEcLow: "推移を継続監視",
    reconciliationTitle: "照合健全度",
    reconciliationSummary: "不足添付、未一致記録、レビュー待ちキューを Dashboard から見える化します。",
    reconciliationBadge: "Dashboard アクションセンター",
    reconciliationInvoice: "不足請求書",
    reconciliationBank: "銀行証憑不足",
    reconciliationReview: "レビュー待ち",
    reconciliationPayout: "未一致入金項目",
    reconciliationPlaceholder: "ドリルダウン準備中",
    accountantTitle: "税理士受け渡し準備度",
    accountantSummary: "月末受け渡し前に、欠票とエクスポート準備状態を見える化します。",
    accountantInvoiceReadiness: "請求書準備度",
    accountantExplainCoverage: "説明カバレッジ",
    accountantReviewBlockers: "レビュー阻害項目",
    accountantChecklistTitle: "月末受け渡しチェックリスト",
    accountantChecklistSummary: "税理士向けエクスポート準備のための軽量協業面です。",
    accountantChecklist: [
      "売上サマリー準備済み",
      "費用添付確認済み",
      "欠票キュー確認済み",
      "入金不一致キュー確認済み",
      "在庫参考出力済み",
      "利益参考確認済み",
    ],
    businessLabels: {
      amazon: "Amazon ビュー",
      ec: "EC ビュー",
      restaurant: "飲食店ビュー",
      generic: "汎用 SMB ビュー",
    },
    businessDescriptions: {
      amazon: "Amazon 売上・入金・差額の理解を中心にした運営ビュー",
      ec: "EC 販売向けの売上・費用・収益管理ビュー",
      restaurant: "飲食店向けの売上・原価・利益確認ビュー",
      generic: "汎用中小事業者向けの経営管理ビュー",
    },
  },
} as const;

export function getDashboardCopy(lang?: string) {
  return copy[normalizeDashboardLocale(lang)];
}
